galaxy_info:
  author: Katharina Reinery
  description: setting up jenkins for CentOS, Debian and Ubuntu

  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: CentOS
      versions:
        - 8
    - name: Debian
      versions:
        - 9
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04


dependencies: 
  - docker